<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>IT Band Systems</Authors>
    <RepositoryUrl>https://github.com/it-band/ITB.CQRS.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>1.8.0</Version>
    <PackageReleaseNotes>Updated to .net 6</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="ITB.Repository.Abstraction" Version="1.8.0" />
    <PackageReference Include="ITB.ResultModel" Version="1.8.0" />
    <PackageReference Include="ITB.Shared.Domain" Version="1.8.0" />
    <PackageReference Include="ITB.Specification" Version="1.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="SimpleInjector" Version="5.4.4" />
  </ItemGroup>

</Project>
